name: "01 - AWS Authentication via OIDC"

on: 
  workflow_dispatch: # manual

permissions:
  id-token: write # GitHub Actions generates Web Identity Token (JWT)
  contents: read # GitHub reads repos

jobs:
  # DebugOIDCJob:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Debug OIDC Token Subject"
  #       run: |
  #         ACTIONS_ID_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
  #           "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')
  #         echo "=== PAYLOAD OIDC ==="
  #         echo "$ACTIONS_ID_TOKEN" | cut -d. -f2 | base64 --decode | jq .
  AssumeRoleJob:
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ARN_AWS_ROLE_OIDC}}
          aws-region: us-east-1
      - name: "Test AWS STS"
        run: aws sts get-caller-identity

