name: "01 - AWS Authentication via OIDC"

on: 
  workflow_dispatch: # manual

permissions:
  id-token: write # GitHub Actions generates Web Identity Token (JWT)
  contents: read # GitHub reads repos

jobs:
  AssumeRoleJob:
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ARN_AWS_ROLE_OIDC}}
          aws-region: us-east-1
      - name: "Test AWS STS"
        run: aws sts get-caller-identity

