# ==============================================================================
# WORKFLOW: 04 - Reusable CD Template (Callable Workflow)
# DESCRIPTION: Standardized, reusable Continuous Delivery job definition triggered via
#              workflow_call. Dynamically binds to GitHub Environments and handles
#              secret inheritance (secrets: inherit) for deployment tasks.
# TARGET CERTIFICATION: GitHub Actions (GH-200) - Domain 1 (Authoring & Managing Workflows) 
#                                               & Domain 3 (Reusability & Extensibility)
# ==============================================================================
name: "04 - Reusable CD Template (Callable Workflow)"

on:
  workflow_call:
    inputs:
      app-name:
        description: "The name of the app"
        required: true
        type: string
      environment:
        description: "A env passed from the caller workflow"
        required: true
        type: string

    secrets:
      LAB04_SECRET_DEPLOY_TOKEN:
        description: "Secret token required for deployment"
        required: true


jobs:
  PrintAndValidateApps:
      runs-on: ubuntu-latest
      environment: ${{ inputs.environment }}

      steps:
        - name: Validate & Display Deployment Info
          run: |
            echo "🚀 Deploying Application: ${{ inputs.app-name }}"
            echo "🌍 Target Environment: ${{ inputs.environment }}"

        - name: Validate DEPLOY_TOKEN
          env:
            DEPLOY_TOKEN: ${{ secrets.LAB04_SECRET_DEPLOY_TOKEN }}
          run: |
            if [ -z "$DEPLOY_TOKEN" ]; then
              echo "❌ Error: DEPLOY_TOKEN secret is not set."
              exit 1
            fi
            echo "✅ DEPLOY_TOKEN verified successfully."

        

